---
- name: Ensure Wildfly is install and running as a service
  hosts: wildfly_servers
  vars_files:
    - vars/vars.yml
  roles:
    - roles/wildfly_install
    - roles/wildfly_systemd
  tasks:
    - name: Install second driver with wildfly_driver role
      ansible.builtin.include_role:
        name: wildfly_driver
      when: jdbc_drivers is defined and jdbc_drivers | length > 0
      vars:
        wildfly_driver_module_name: "{{ item.name }}"
        wildfly_driver_version: "{{ item.version }}"
        wildfly_driver_jar_filename: "{{ item.jar_file }}"
        wildfly_driver_jar_url: "{{ item.url }}"
      loop: "{{ jdbc_drivers }}"

